"""Add file_url to courses table

Revision ID: 138c8cda8cdd
Revises: f1e598540bc1
Create Date: 2025-11-18 14:14:16.838377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138c8cda8cdd'
down_revision = 'f1e598540bc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('file_url', sa.String(), nullable=True))
    op.alter_column('courses', 'original_text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'original_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('courses', 'file_url')
    # ### end Alembic commands ###
